/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

#include <casadi/mem.h>
int solveQP(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int solveQP_alloc_mem(void);
int solveQP_init_mem(int mem);
void solveQP_free_mem(int mem);
int solveQP_checkout(void);
void solveQP_release(int mem);
void solveQP_incref(void);
void solveQP_decref(void);
casadi_int solveQP_n_in(void);
casadi_int solveQP_n_out(void);
casadi_real solveQP_default_in(casadi_int i);
const char* solveQP_name_in(casadi_int i);
const char* solveQP_name_out(casadi_int i);
const casadi_int* solveQP_sparsity_in(casadi_int i);
const casadi_int* solveQP_sparsity_out(casadi_int i);
int solveQP_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solveQP_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define solveQP_SZ_ARG 24
#define solveQP_SZ_RES 14
#define solveQP_SZ_IW 0
#define solveQP_SZ_W 139
casadi_functions* solveQP_functions(void);
#ifdef __cplusplus
} /* extern "C" */
#endif
